### ISSUE TITLE
TODO Week of January 22

### ISSUE THREAD

**Issue by raynamharris** [raynamharris/cefp2019#1]
- [x] fill out [community coins](https://github.com/raynamharris/cefp2019/issues/3)
- [x] revisit sci comm engagement manuscript based on new info learned at training and rstudioconf
- [x] start slide deck for lab meeting presentation about CEFP and rstudio conf
- [x] submit CEFP reimbursements
